import {
  Agent,
  Recommendation,
  OptimizationScore,
  ImpactDataPoint,
  ChatMessage,
  ActivityEvent,
  KnowledgeStats,
} from "./types";

export const mockAgents: Agent[] = [
  {
    id: 1,
    name: "// 01 — Analyzer",
    role: "Sage",
    codename: "sage",
    status: "analyzing",
    task: "Embedding 14k query patterns from JOBS_TIMELINE",
    active: true,
  },
  {
    id: 2,
    name: "// 02 — Optimizer",
    role: "Forge",
    codename: "forge",
    status: "planning",
    task: "Ranking 23 candidate index strategies",
    active: true,
  },
  {
    id: 3,
    name: "// 03 — Simulator",
    role: "Echo",
    codename: "echo",
    status: "dry-run",
    task: "Replaying 50 queries on shadow clone",
    active: true,
  },
  {
    id: 4,
    name: "// 04 — Applier",
    role: "Wright",
    codename: "wright",
    status: "awaiting approval",
    task: "2 DDL statements queued",
    active: false,
  },
  {
    id: 5,
    name: "// 05 — Historian",
    role: "Codex",
    codename: "codex",
    status: "indexing",
    task: "Writing decision lineage to graph",
    active: true,
  },
];

export const mockRecommendations: Recommendation[] = [
  {
    id: "rec-001",
    database_type: "BigQuery",
    recommendation_type: "Partitioning",
    agents: "Sage + Forge",
    severity: "high",
    title:
      'Repartition <code>events_raw</code> by <code>DATE(event_ts)</code> + cluster on <code>user_id</code>',
    target: "analytics-prod.warehouse.events_raw · 4.2 TB · 3.1B rows",
    description:
      "94% of queries on this table filter by event_ts in a ≤30-day window, but the table is currently unpartitioned. Adding daily partitioning + clustering should cut average bytes-scanned by an estimated 87%.",
    sql: `-- Generated by Forge · simulated by Echo
CREATE OR REPLACE TABLE warehouse.events_raw
PARTITION BY DATE(event_ts)
CLUSTER BY user_id, event_type
AS SELECT * FROM warehouse.events_raw;`,
    impact: [
      { label: "Bytes scanned", value: "−87%", positive: true },
      { label: "Est. monthly savings", value: "$12.4K", positive: true },
      { label: "Avg query", value: "4.2× faster", positive: true },
      { label: "Risk", value: "medium", positive: false },
    ],
    icon_type: "cost",
    actions: ["apply", "simulate", "reject"],
  },
  {
    id: "rec-002",
    database_type: "AlloyDB",
    recommendation_type: "Index",
    agents: "Forge",
    severity: "medium",
    title:
      'Add composite B-tree index on <code>orders(customer_id, status, created_at)</code>',
    target: "customer-360.public.orders · 280M rows",
    description:
      "The customer dashboard query pattern shows repeated scans filtering on these three columns together. EXPLAIN ANALYZE shows a sequential scan costing 1.8s p95.",
    impact: [
      { label: "p95 latency", value: "1.8s → 84ms", positive: true },
      { label: "Slot hours/day", value: "−18%", positive: true },
      { label: "Storage", value: "+2.1 GB", positive: false },
    ],
    icon_type: "perf",
    actions: ["apply", "simulate", "reject"],
  },
  {
    id: "rec-003",
    database_type: "BigQuery ML",
    recommendation_type: "Drift detected",
    agents: "Sage",
    severity: "medium",
    title:
      'Retrain <code>churn_predictor_v3</code> — feature distribution drift > 0.18',
    target:
      "ml-models.production.churn_predictor_v3 · last trained 47 days ago",
    description:
      "PSI for days_since_last_login exceeded threshold 12 days ago. Recent predictions showing 7% degradation in F1 vs baseline.",
    impact: [
      { label: "Drift score", value: "0.184", positive: false },
      { label: "Est. accuracy regain", value: "+6.2%", positive: true },
      { label: "Train cost", value: "$84", positive: false },
    ],
    icon_type: "warn",
    actions: ["schedule", "review", "snooze"],
  },
  {
    id: "rec-004",
    database_type: "Spanner",
    recommendation_type: "Hot spot",
    agents: "Sage + Forge",
    severity: "high",
    title:
      'Add hash prefix to <code>transaction_log</code> primary key to relieve range hot-spot',
    target: "payments-prod.ledger.transaction_log · 12 splits, 1 hot",
    description:
      "Load-based splitting shows a single split absorbing 38% of writes. Hashing the leading region_id column should distribute load across all splits.",
    impact: [
      { label: "Write latency p99", value: "240ms → ~60ms", positive: true },
      { label: "Migration", value: "requires backfill", positive: false },
      { label: "Risk", value: "high", positive: false },
    ],
    icon_type: "perf",
    actions: ["plan_migration", "simulate", "reject"],
  },
  {
    id: "rec-005",
    database_type: "BigQuery",
    recommendation_type: "Staleness detected",
    agents: "Sage",
    severity: "medium",
    title:
      'Refresh Materialized View <code>daily_sales_summary</code> — staleness > 48 hours',
    target: "analytics-prod.reporting.daily_sales_summary",
    description:
      "The materialized view has not automatically refreshed due to an upstream schema change in base tables blocking the internal refresh job. 14 critical executive dashboards are currently serving stale data.",
    sql: `-- Generated by Forge
CALL BQ.REFRESH_MATERIALIZED_VIEW('analytics-prod.reporting.daily_sales_summary');`,
    impact: [
      { label: "Data freshness", value: "Stale (48h)", positive: false },
      { label: "Impact", value: "14 dashboards", positive: false },
    ],
    icon_type: "warn",
    actions: ["apply", "reject"],
  },
  {
    id: "rec-006",
    database_type: "AlloyDB",
    recommendation_type: "Optimization Gap",
    agents: "Forge + Codex",
    severity: "low",
    title:
      'Add missing Foreign Key constraint on <code>user_sessions(user_id)</code>',
    target: "auth-db.public.user_sessions",
    description:
      "Identified an implicit relationship with `users(id)` through query JOIN patterns. Adding an explicit Foreign Key will improve query optimizer join planning and enforce data integrity.",
    sql: `-- Generated by Forge
ALTER TABLE public.user_sessions
ADD CONSTRAINT fk_user_sessions_users
FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`,
    impact: [
      { label: "Data Integrity", value: "Enforced", positive: true },
      { label: "Join performance", value: "+4%", positive: true },
    ],
    icon_type: "perf",
    actions: ["apply", "simulate", "reject"],
  },
];

export const mockOptimizationScore: OptimizationScore = {
  score: 85,
  grade: "B+ · Healthy",
  trend: "↑ +14 pts · 30d",
  description: "17 optimizations applied this month. Score up from 71.",
  cost_saved: 28400,
  cost_trend: "↑ 32% vs last month",
  speedup: 3.7,
  speedup_trend: "↑ 0.4× this week",
  pending: 8,
  pending_high: 3,
};

export function generateImpactTimeline(days: number = 30): ImpactDataPoint[] {
  const data: ImpactDataPoint[] = [];
  const now = new Date();
  const appliedDays = [5, 12, 20, 26];

  for (let i = days - 1; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    const progress = (days - i) / days;
    data.push({
      date: date.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
      bytes_scanned: +(12.5 - 4.2 * progress + (Math.random() - 0.5) * 1.2).toFixed(1),
      avg_latency: +(850 - 280 * progress + (Math.random() - 0.5) * 80).toFixed(0),
      applied: appliedDays.includes(days - 1 - i),
    });
  }
  return data;
}

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    role: "user",
    content: "Why is <code>customer_360_dashboard</code> 3× slower this week?",
  },
  {
    id: "msg-2",
    role: "ai",
    content:
      'Sage traced the regression to a <code>JOIN</code> against <code>orders_v2</code> that grew from 180M → 280M rows after the April 18 migration. The existing index on <code>(customer_id)</code> no longer satisfies the query — it now needs a composite key.',
    reasoning:
      "Investigated 47 query executions over 7 days. P95 latency shifted from 220ms → 680ms on Apr 19. EXPLAIN plan changed: nested loop → hash join. Index recommendation queued as Rec #2 above.",
  },
  {
    id: "msg-3",
    role: "user",
    content: "What's the rollback plan if Rec #1 goes wrong?",
  },
  {
    id: "msg-4",
    role: "ai",
    content:
      'Wright will use a CTAS pattern: the old table is preserved as <code>events_raw__pre_evo_1247</code> for 7 days. Cutover happens via atomic table-swap. Rollback = single <code>ALTER TABLE … RENAME</code> (≈3s).',
    reasoning:
      "Pulled rollback playbook v4 from Codex's knowledge graph. 12 similar repartition operations executed previously, 0 incidents, 1 rollback used (Feb 14 — schema mismatch caught in 90s).",
  },
];

export const mockActivityEvents: ActivityEvent[] = [
  {
    id: "act-1",
    timestamp: "04:42:11",
    agent: "SAGE",
    content: "Identified high-scan pattern on",
    dot_type: "accent",
    highlight: "events_raw, 94% temporal-filtered",
  },
  {
    id: "act-2",
    timestamp: "04:42:38",
    agent: "FORGE",
    content: "Generated 5 candidate strategies, ranked by simulated impact",
    dot_type: "accent",
  },
  {
    id: "act-3",
    timestamp: "04:43:02",
    agent: "ECHO",
    content: "Cloned",
    dot_type: "info",
    highlight: "events_raw to shadow dataset (2% sample, 84M rows)",
  },
  {
    id: "act-4",
    timestamp: "04:44:17",
    agent: "ECHO",
    content: "Replayed 50-query benchmark on shadow · −87% bytes confirmed",
    dot_type: "info",
  },
  {
    id: "act-5",
    timestamp: "04:44:51",
    agent: "CODEX",
    content:
      "Cross-referenced 4 prior repartitions on similar tables — all positive",
    dot_type: "warn",
  },
  {
    id: "act-6",
    timestamp: "04:45:09",
    agent: "COORD",
    content: "Recommendation surfaced for human review · awaiting decision",
    dot_type: "accent",
  },
];

export const mockKnowledgeStats: KnowledgeStats = {
  decisions_logged: 2841,
  patterns_learned: 147,
  rollbacks_90d: 3,
  confidence_avg: 94,
};
