from fastapi import APIRouter
from models.schemas import Recommendation, ApplyResult, RejectResult, SimulateResult, Impact
import uuid

router = APIRouter()

MOCK_RECS = [
    Recommendation(
        id="rec-001",
        database_type="BigQuery",
        recommendation_type="Partitioning",
        agents="Sage + Forge",
        severity="high",
        title='Repartition <code>events_raw</code> by <code>DATE(event_ts)</code> + cluster on <code>user_id</code>',
        target="analytics-prod.warehouse.events_raw · 4.2 TB · 3.1B rows",
        description="94% of queries on this table filter by event_ts in a ≤30-day window, but the table is currently unpartitioned. Adding daily partitioning + clustering should cut average bytes-scanned by an estimated 87%.",
        sql="""-- Generated by Forge · simulated by Echo
CREATE OR REPLACE TABLE warehouse.events_raw
PARTITION BY DATE(event_ts)
CLUSTER BY user_id, event_type
AS SELECT * FROM warehouse.events_raw;""",
        impact=[
            Impact(label="Bytes scanned", value="−87%", positive=True),
            Impact(label="Est. monthly savings", value="$12.4K", positive=True),
            Impact(label="Avg query", value="4.2× faster", positive=True),
            Impact(label="Risk", value="medium", positive=False),
        ],
        icon_type="cost",
        actions=["apply", "simulate", "reject"],
    ),
    Recommendation(
        id="rec-002",
        database_type="AlloyDB",
        recommendation_type="Index",
        agents="Forge",
        severity="medium",
        title='Add composite B-tree index on <code>orders(customer_id, status, created_at)</code>',
        target="customer-360.public.orders · 280M rows",
        description="The customer dashboard query pattern shows repeated scans filtering on these three columns together. EXPLAIN ANALYZE shows a sequential scan costing 1.8s p95.",
        impact=[
            Impact(label="p95 latency", value="1.8s → 84ms", positive=True),
            Impact(label="Slot hours/day", value="−18%", positive=True),
            Impact(label="Storage", value="+2.1 GB", positive=False),
        ],
        icon_type="perf",
        actions=["apply", "simulate", "reject"],
    ),
    Recommendation(
        id="rec-003",
        database_type="BigQuery ML",
        recommendation_type="Drift detected",
        agents="Sage",
        severity="medium",
        title='Retrain <code>churn_predictor_v3</code> — feature distribution drift > 0.18',
        target="ml-models.production.churn_predictor_v3 · last trained 47 days ago",
        description="PSI for days_since_last_login exceeded threshold 12 days ago. Recent predictions showing 7% degradation in F1 vs baseline.",
        impact=[
            Impact(label="Drift score", value="0.184", positive=False),
            Impact(label="Est. accuracy regain", value="+6.2%", positive=True),
            Impact(label="Train cost", value="$84", positive=False),
        ],
        icon_type="warn",
        actions=["schedule", "review", "snooze"],
    ),
    Recommendation(
        id="rec-004",
        database_type="Spanner",
        recommendation_type="Hot spot",
        agents="Sage + Forge",
        severity="high",
        title='Add hash prefix to <code>transaction_log</code> primary key to relieve range hot-spot',
        target="payments-prod.ledger.transaction_log · 12 splits, 1 hot",
        description="Load-based splitting shows a single split absorbing 38% of writes. Hashing the leading region_id column should distribute load across all splits.",
        impact=[
            Impact(label="Write latency p99", value="240ms → ~60ms", positive=True),
            Impact(label="Migration", value="requires backfill", positive=False),
            Impact(label="Risk", value="high", positive=False),
        ],
        icon_type="perf",
        actions=["plan_migration", "simulate", "reject"],
    ),
    Recommendation(
        id="rec-005",
        database_type="BigQuery",
        recommendation_type="Staleness detected",
        agents="Sage",
        severity="medium",
        title='Refresh Materialized View <code>daily_sales_summary</code> — staleness > 48 hours',
        target="analytics-prod.reporting.daily_sales_summary",
        description="The materialized view has not automatically refreshed due to an upstream schema change in base tables blocking the internal refresh job. 14 critical executive dashboards are currently serving stale data.",
        sql="-- Generated by Forge\nCALL BQ.REFRESH_MATERIALIZED_VIEW('analytics-prod.reporting.daily_sales_summary');",
        impact=[
            Impact(label="Data freshness", value="Stale (48h)", positive=False),
            Impact(label="Impact", value="14 dashboards", positive=False),
        ],
        icon_type="warn",
        actions=["apply", "reject"],
    ),
    Recommendation(
        id="rec-006",
        database_type="AlloyDB",
        recommendation_type="Optimization Gap",
        agents="Forge + Codex",
        severity="low",
        title='Add missing Foreign Key constraint on <code>user_sessions(user_id)</code>',
        target="auth-db.public.user_sessions",
        description="Identified an implicit relationship with `users(id)` through query JOIN patterns. Adding an explicit Foreign Key will improve query optimizer join planning and enforce data integrity.",
        sql="-- Generated by Forge\nALTER TABLE public.user_sessions\nADD CONSTRAINT fk_user_sessions_users\nFOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;",
        impact=[
            Impact(label="Data Integrity", value="Enforced", positive=True),
            Impact(label="Join performance", value="+4%", positive=True),
        ],
        icon_type="perf",
        actions=["apply", "simulate", "reject"],
    ),
]


@router.get("/recommendations")
async def list_recommendations():
    return MOCK_RECS


@router.get("/recommendations/{rec_id}")
async def get_recommendation(rec_id: str):
    for rec in MOCK_RECS:
        if rec.id == rec_id:
            return {
                **rec.model_dump(),
                "simulation_results": {
                    "before_plan": "Seq Scan on events_raw (cost=0.00..1847293.00 rows=3100000000 width=128)",
                    "after_plan": "Index Scan using events_raw_partition_idx (cost=0.43..8.45 rows=1 width=128)",
                    "bytes_before": 4200000000000,
                    "bytes_after": 546000000000,
                    "latency_before_ms": 8400,
                    "latency_after_ms": 2000,
                },
            }
    return {"error": "not found"}, 404


@router.post("/recommendations/{rec_id}/apply")
async def apply_recommendation(rec_id: str):
    return ApplyResult(status="applied", change_id=str(uuid.uuid4()))


@router.post("/recommendations/{rec_id}/reject")
async def reject_recommendation(rec_id: str):
    return RejectResult(status="rejected")


@router.post("/recommendations/{rec_id}/simulate")
async def simulate_recommendation(rec_id: str):
    return SimulateResult(
        before_plan="Seq Scan on events_raw (cost=0.00..1847293.00 rows=3100000000 width=128)\n  Filter: (event_ts >= '2024-03-01'::date AND event_ts <= '2024-03-31'::date)",
        after_plan="Index Scan using events_raw_part_idx on events_raw_20240301 (cost=0.43..8.45 rows=1 width=128)\n  Index Cond: (event_ts >= '2024-03-01' AND event_ts <= '2024-03-31')",
        bytes_before=4200000000000,
        bytes_after=546000000000,
        latency_before_ms=8400,
        latency_after_ms=2000,
    )
